### ISSUE TITLE
Abandoned? 

### ISSUE THREAD

**Issue by asecondwill** [burnbright/silverstripe-shop-taxframework#6]
I can't run dev/build if i download the module to my project.  no composer info. probably not a current module? has it been replaced? 

Fatal error: Class 'DataObjectDecorator' not found in TaxedProductDecorator.php on line 3

**Comment by wilr** [comment]
`DataObjectDecorator` is SilverStripe 2.0 syntax so yes, you can assume this is abandoned for new projects

**Comment by asecondwill** [comment]
ok, thanks.
